### create a feeling
POST http://localhost:4002/moods/create-mood
Content-Type: application/json

{
  "feeling": "happy"
}

### get all moods
GET http://localhost:4002/moods
Content-Type: application/json

### get a mood by id
GET http://localhost:4002/moods/2
Content-Type: application/json

### update a mood by id
PATCH http://localhost:4002/moods/3
Content-Type: application/json

{
  "feeling": "sad"
}

### delete a mood by id
DELETE http://localhost:4002/moods/2
Content-Type: application/json

### get mood with a specific feeling

GET http://localhost:4002/movies?mood=joy
Content-Type: application/json